-- Oleada 1 legacy: maestros + agenda + planinc + bonos cliente + facturas (sin TMP)
-- Generado por scripts/build_legacy_wave1_migration.py

CREATE SCHEMA IF NOT EXISTS legacy;

COMMENT ON SCHEMA legacy IS 'Volcado fiel Dunasoft/Style (oleada 1). No exponer a API publica sin revision.';

REVOKE ALL ON SCHEMA legacy FROM PUBLIC;
GRANT USAGE ON SCHEMA legacy TO postgres;
GRANT USAGE ON SCHEMA legacy TO service_role;

CREATE TABLE IF NOT EXISTS legacy.clientes (
  vipsalon text,
  noemail text,
  nosms text,
  codcli text,
  nomcli text,
  ape1cli text,
  email text,
  dnicli text,
  dircli text,
  codposcli text,
  pobcli text,
  procli text,
  asenta text,
  pais text,
  tel1cli text,
  tel2cli text,
  foto text,
  tipcli text,
  obscli text,
  dtopp text,
  dto1 text,
  forpagcli text,
  fijo1 text,
  fijo2 text,
  fijo3 text,
  numpag text,
  pripag text,
  entpag text,
  deuda text,
  codemp text,
  faxcli text,
  puntos text,
  tarifa text,
  fecnac text,
  enviar text,
  sexo text,
  obslopdo text,
  tipcuecabp text,
  tipcabp text,
  estcabp text,
  proutip text,
  sesionesp text,
  frecuenp text,
  fecinip text,
  fecfinp text,
  prouticp text,
  formulasp text,
  tecnicap text,
  tieexpp text,
  pesoe text,
  tippiee text,
  embarazoe text,
  alergiase text,
  marcape text,
  protesise text,
  heridase text,
  operacione text,
  tiroidese text,
  anticone text,
  tensione text,
  enfnonome text,
  proutie text,
  sesionese text,
  frecuene text,
  fecinie text,
  fecfine text,
  diabetese text,
  obsoleto text,
  codalu text,
  codcue text,
  idtipcli text,
  codcli2 text,
  codproce text,
  doclopd text,
  percon text,
  fecalta text,
  essocio text,
  fecaltsoc text,
  fecbajsoc text,
  codban text,
  cueban text,
  altura text,
  concor text,
  bonosneg text,
  codemppel text,
  codempest text,
  profesion text,
  menprovis text,
  siniva text,
  conrec text,
  idcenalta text,
  nomcen text,
  numcalle text,
  numpiso text,
  enviarand text,
  iban text,
  swift text,
  idmansepa text,
  fecmansepa text,
  enviarcro text,
  actpuntos text,
  opcpuntos text,
  codclienl text,
  idioma text,
  envticmail text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_clientes_imported_at ON legacy.clientes (imported_at);

CREATE TABLE IF NOT EXISTS legacy.empleados (
  codemp text,
  nomemp text,
  ape1emp text,
  ape2emp text,
  dniemp text,
  diremp text,
  codposemp text,
  pobemp text,
  proemp text,
  asenta text,
  pais text,
  tel1emp text,
  tel2emp text,
  tel3emp text,
  foto text,
  tipemp text,
  obsemp text,
  comision text,
  obsoleto text,
  fecbaja text,
  lunes text,
  martes text,
  miercoles text,
  jueves text,
  viernes text,
  sabado text,
  domingo text,
  codemp2 text,
  tipcom text,
  barprod text,
  barserv text,
  dia1a text,
  dia1b text,
  dia1c text,
  dia1d text,
  dia2a text,
  dia2b text,
  dia2c text,
  dia2d text,
  dia3a text,
  dia3b text,
  dia3c text,
  dia3d text,
  dia4a text,
  dia4b text,
  dia4c text,
  dia4d text,
  dia5a text,
  dia5b text,
  dia5c text,
  dia5d text,
  dia6a text,
  dia6b text,
  dia6c text,
  dia6d text,
  dia7a text,
  dia7b text,
  dia7c text,
  dia7d text,
  verplan text,
  ordplan text,
  colorpf text,
  colorpl text,
  enviar text,
  allcentros text,
  enviarweb text,
  envfotweb text,
  enviarcro text,
  titaddi text,
  obsaddi text,
  facebook text,
  twitter text,
  instagram text,
  ordaddi text,
  idcatemp text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_empleados_imported_at ON legacy.empleados (imported_at);

CREATE TABLE IF NOT EXISTS legacy.articulos (
  codart text,
  codartdos text,
  desart text,
  familia1 text,
  foto text,
  tipart text,
  codpro text,
  coste text,
  pvpa text,
  pvpb text,
  pvpc text,
  pvpd text,
  pvpe text,
  stock text,
  pedido text,
  obsart text,
  ivaart text,
  matpri text,
  enviar text,
  vender text,
  porpvpa text,
  porpvpb text,
  porpvpc text,
  porpvpd text,
  porpvpe text,
  pvpvar text,
  avichgpvp text,
  desartcort text,
  obsoleto text,
  tiempo text,
  idpuesto text,
  bascula text,
  orden text,
  ntickets text,
  codcuev text,
  codcuec text,
  pedpvp text,
  peddes text,
  stomin text,
  stomax text,
  creditos text,
  colorf text,
  colorl text,
  contallas text,
  enviarweb text,
  envfotweb text,
  pvpcoma text,
  pvpcomb text,
  pvpcomc text,
  pvpcomd text,
  pvpcome text,
  puntos text,
  pedpulsos text,
  idtipart text,
  dtov text,
  dtoc text,
  actnumser text,
  motexeiva text,
  poremps text,
  prestashop text,
  presenv text,
  prestags text,
  presmettit text,
  presmetkey text,
  presmetdes text,
  presurl text,
  prescosenv text,
  prescodart text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_articulos_imported_at ON legacy.articulos (imported_at);

CREATE TABLE IF NOT EXISTS legacy.agenda (
  apentrada text,
  codage text,
  dia text,
  hora text,
  cliente text,
  codemp text,
  obsage text,
  facturado text,
  clientebd text,
  agendaweb text,
  enviar text,
  idplan text,
  horfin text,
  tel1cli text,
  idusuweb text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_agenda_imported_at ON legacy.agenda (imported_at);

CREATE TABLE IF NOT EXISTS legacy.planinc (
  idplaninc text,
  codusu text,
  fechorinc text,
  tipinc text,
  idplan text,
  codemp text,
  codcli text,
  fecha text,
  horini text,
  horfin text,
  texto text,
  codrec text,
  nomcli text,
  tel1cli text,
  planart text,
  codempx text,
  codclix text,
  fechax text,
  horinix text,
  horfinx text,
  textox text,
  codrecx text,
  nomclix text,
  tel1clix text,
  planartx text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_planinc_imported_at ON legacy.planinc (imported_at);

CREATE TABLE IF NOT EXISTS legacy.bonoscli (
  codboncli text,
  codcli text,
  fecha text,
  fecven text,
  importe text,
  dto text,
  impgas text,
  obsboncli text,
  codemp text,
  nocaduca text,
  codbon text,
  ntickets text,
  ticgas text,
  enviar text,
  finalizado text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_bonoscli_imported_at ON legacy.bonoscli (imported_at);

CREATE TABLE IF NOT EXISTS legacy.faccab (
  serfac text,
  ejefac text,
  numfac text,
  fecfac text,
  hora text,
  codcli text,
  obsfac text,
  impbas1 text,
  impbas2 text,
  impbas3 text,
  impbas4 text,
  impiva1 text,
  impiva2 text,
  impiva3 text,
  impiva4 text,
  iva1 text,
  iva2 text,
  iva3 text,
  iva4 text,
  totimpbas text,
  totimpdto text,
  totimpiva text,
  totfac text,
  lineas text,
  impresa text,
  fijo1 text,
  fijo2 text,
  fijo3 text,
  numpag text,
  pripag text,
  entpag text,
  dtopp text,
  dto1 text,
  poliza text,
  codban text,
  cueban text,
  dtocam text,
  dtoaso text,
  dtomav text,
  dtovar text,
  anulada text,
  puntos text,
  codemp text,
  impcob1 text,
  forpag1 text,
  impcob2 text,
  forpag2 text,
  impcam text,
  cierre text,
  foto1 text,
  foto2 text,
  enviar text,
  sexo text,
  idconcepto text,
  codboncli1 text,
  codboncli2 text,
  impbono1 text,
  impbono2 text,
  mesa text,
  comensales text,
  actrec text,
  rec1 text,
  rec2 text,
  rec3 text,
  rec4 text,
  imprec1 text,
  imprec2 text,
  imprec3 text,
  imprec4 text,
  totimprec text,
  actirpfp text,
  irpfp text,
  impirpfp text,
  numfacrel text,
  ntickets text,
  codalu text,
  ticeval text,
  contab text,
  idfactura text,
  bloqueado text,
  fechorfin text,
  facimp text,
  numprerel text,
  numalbrel text,
  ntickets1 text,
  ntickets2 text,
  hash text,
  hash1 text,
  cert text,
  nocert text,
  folfis text,
  fecfolfis text,
  hashsat text,
  hash1sat text,
  nocertsat text,
  rutaqr text,
  timbrepac text,
  horasaft text,
  iban text,
  siniva text,
  rfcsat text,
  leysat text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_faccab_imported_at ON legacy.faccab (imported_at);

CREATE TABLE IF NOT EXISTS legacy.faclin (
  serfac text,
  ejefac text,
  numfac text,
  linfac text,
  codart text,
  desart text,
  tipfam1 text,
  preven text,
  coste text,
  cant text,
  subtot text,
  descuento text,
  taniva text,
  obser text,
  codemp text,
  comision text,
  codboncli text,
  codbon text,
  estado text,
  hora text,
  impreso text,
  plato text,
  poremps text,
  codemp2 text,
  comision2 text,
  creditos text,
  codalu text,
  idtalla text,
  idcolor text,
  pvpcom text,
  pulsos text,
  energia text,
  numalb text,
  seralb text,
  ejealb text,
  linalb text,
  numser text,
  import_batch text NOT NULL DEFAULT '',
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legacy_faclin_imported_at ON legacy.faclin (imported_at);

